# netlify.toml
[build]
  command = "npm --prefix calendar-app-mobile/calendar-app-mobile install && npm --prefix calendar-app-mobile/calendar-app-mobile run build"
  publish = "calendar-app-mobile/calendar-app-mobile/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200